---
- name: Jinja Templating example
  hosts: dbserver
  become: true
  become_user: root
  vars:
   ansible_python_interpreter: /usr/bin/python3.6
  tasks:
  - name: Update Jinga playbook template
    template:
     src: example.j2
     dest: /home/output.txt