---

- name: Install nginx and enable it
  hosts: dbserver
  become: true
  tasks: 
  - name: Install Nginx
    yum:
     name: nginx
     state: latest
     
  - name: Start Nginx Service
    service:
     name: nginx
     state: started
     