---
- name: Install python3.6 on DBServer
  hosts: dbserver
  tasks: 
  - name: update yum repo 
    become: true
    yum:  
     name: '*'
     state: latest     
     
  - name: install python3 in dbserver
    become: true
    yum:  
     name:  
      - python3
      - python3-pip
     state: present
     
     
     


 
 